@startuml
skinparam participantStyle Rectangle
skinparam shadowing false
skinparam ArrowFontStyle plain
skinparam BoxPadding 10
skinparam sequence {
    LifeLineBorderColor black
    LifeLineBackgroundColor #F8F8F8
    ParticipantBorderColor black
    ParticipantBackgroundColor #EAEAEA
    BoxBorderColor black
}

box "UI Layer" #LightBlue
participant "User" as User
participant ":UI" as UI
end box

box "Logic Layer" #LightYellow
participant ":LogicManager" as LogicManager
participant ":SummonersBookParser" as SummonersBookParser
participant ":FilterCommandParser" as FilterCommandParser
participant "FilterCommand.FilterPlayerDescriptor" as FilterPlayerDescriptor
participant "f:FilterCommand" as FilterCommand
end box

box "Model Layer" #LightGreen
participant ":Model" as Model
end box

== User inputs command ==
User -> UI : enter "filter rk/Diamond c/Yasuo"
activate UI

UI -> LogicManager : execute("filter rk/Diamond c/Yasuo")
activate LogicManager

== Parsing ==
LogicManager -> SummonersBookParser : parseCommand("filter rk/Diamond c/Yasuo")
activate SummonersBookParser

SummonersBookParser -> FilterCommandParser : parse("rk/Diamond c/Yasuo")
activate FilterCommandParser

== Build FilterPlayerDescriptor ==
create FilterPlayerDescriptor
FilterCommandParser -> FilterPlayerDescriptor : FilterPlayerDescriptor()
activate FilterPlayerDescriptor
FilterPlayerDescriptor --> FilterCommandParser
deactivate FilterPlayerDescriptor

FilterCommandParser -> FilterCommandParser : parseRanksForFilter()
FilterCommandParser -> FilterPlayerDescriptor : setRanks(Set<Rank>)
activate FilterPlayerDescriptor
FilterPlayerDescriptor --> FilterCommandParser
deactivate FilterPlayerDescriptor
FilterCommandParser -> FilterCommandParser : parseRolesForFilter()
FilterCommandParser -> FilterCommandParser : parseChampionsForFilter()
FilterCommandParser -> FilterPlayerDescriptor : setChampions(Set<Champion>)
activate FilterPlayerDescriptor
FilterPlayerDescriptor --> FilterCommandParser
deactivate FilterPlayerDescriptor


== Create FilterCommand ==
create FilterCommand
FilterCommandParser -> FilterCommand : FilterCommand(filterPlayerDescriptor)
activate FilterCommand
FilterCommand --> FilterCommandParser
deactivate FilterCommand

FilterCommandParser --> SummonersBookParser : f
deactivate FilterCommandParser

SummonersBookParser --> LogicManager : f
deactivate SummonersBookParser

== Executing ==
LogicManager -> FilterCommand : execute(model)
activate FilterCommand

FilterCommand -> Model : updateFilteredPlayerList(rank ∧ role ∧ champion predicates)
activate Model

Model --> FilterCommand : (updated filtered list)
deactivate Model

FilterCommand --> LogicManager : CommandResult (filtered list message)
deactivate FilterCommand

LogicManager --> UI : CommandResult
deactivate LogicManager

UI --> User : display filtered list
deactivate UI

@enduml
