@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SummonersBookParser" as SummonersBookParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":PlayerDetailWindow" as PlayerDetailWindow UI_COLOR
end box

[-> LogicManager : execute("view 1")
activate LogicManager

LogicManager -> SummonersBookParser : parseCommand("view 1")
activate SummonersBookParser

create ViewCommandParser
SummonersBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> SummonersBookParser
deactivate ViewCommandParser

SummonersBookParser -> ViewCommandParser : parse("1")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser
deactivate ViewCommand

ViewCommandParser --> SummonersBookParser : v
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> SummonersBookParser
destroy ViewCommandParser

SummonersBookParser --> LogicManager : v
deactivate SummonersBookParser

LogicManager -> ViewCommand : execute(m)
activate ViewCommand

ViewCommand -> Model : getFilteredPlayerList()
activate Model

Model --> ViewCommand : playerList
deactivate Model

create CommandResult
ViewCommand -> CommandResult : showPlayerDetail(message, player)
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : r
deactivate ViewCommand

LogicManager --> MainWindow : r
deactivate LogicManager

MainWindow -> MainWindow : handleCommandResult(r)
activate MainWindow

MainWindow -> CommandResult : isShowPlayerDetail()
activate CommandResult

CommandResult --> MainWindow : true
deactivate CommandResult

MainWindow -> CommandResult : getPlayerToShow()
activate CommandResult

CommandResult --> MainWindow : player
deactivate CommandResult

create PlayerDetailWindow
MainWindow -> PlayerDetailWindow : new PlayerDetailWindow()
activate PlayerDetailWindow

PlayerDetailWindow --> MainWindow
deactivate PlayerDetailWindow

MainWindow -> PlayerDetailWindow : setPlayer(player)
activate PlayerDetailWindow

PlayerDetailWindow --> MainWindow
deactivate PlayerDetailWindow

MainWindow -> PlayerDetailWindow : show()
activate PlayerDetailWindow

PlayerDetailWindow --> MainWindow
deactivate PlayerDetailWindow

deactivate MainWindow

@enduml
